#!/bin/bash

target_id="$1"
if [ -z "$target_id" ]
then
  echo "Usage: $0 target_id"
  exit 1
fi

echo '{'

echo -n 'x: ['
for file in data/*.log
do
  echo -n "'$(echo "$file" | sed 's/.*\([0-9][0-9][0-9][0-9]\)\([0-9][0-9]\)\([0-9][0-9]\).*/\1-\2-\3/')', "
done
echo '],'

echo -n 'y: ['
for file in data/*.log
do
  echo -n "$((5 * $(grep "$target_id" "$file" | wc -l))), "
done
echo ']'

echo '}'
